'use strict'

import './modules/swiper.js';
import './modules/setCatalogHeight.js';
import './modules/openCatalogMenu.js';
import './modules/limitStrs.js';
import './modules/mobileMenuOpener.js';
import './modules/mobileMenuCatalog.js';
import './modules/productCardDetail.js';
import './modules/cartAddBtns.js';
import './modules/cartCounter.js';
import './modules/custom_select.js';
import './modules/nouislider.js';
import './modules/filterDropdown.js';
import './modules/openFilter.js';
import './modules/tabs.js';
import './modules/accordeon.js';
import './modules/zoom.js';
import './modules/birthPicker.js';
import './modules/modalOpener.js';
